# Generated by Django 4.0.6 on 2022-07-22 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=6)),
                ('image_url', models.URLField()),
            ],
            options={
                'verbose_name': 'FII',
                'verbose_name_plural': 'FIIs',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nr_nota', models.IntegerField()),
                ('tipo', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda'), ('D', 'Desdobramento'), ('A', 'Amortização')], max_length=1)),
                ('preco', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('custos', models.FloatField()),
                ('contabil', models.FloatField()),
                ('total_nota', models.FloatField()),
                ('soma_quantidade', models.FloatField()),
                ('soma_total', models.FloatField()),
                ('preco_medio', models.FloatField()),
                ('fii', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fii.fii')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fii_operacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='FIIByUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fii', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fii.fii')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FII',
                'verbose_name_plural': 'FIIs',
                'ordering': ['fii'],
                'unique_together': {('fii', 'user')},
            },
        ),
    ]
